<?php


namespace calderawp\caldera\restApi\Tests;

use calderawp\caldera\core\CalderaCore;
use calderawp\caldera\Events\CalderaEvents;
use calderawp\caldera\restApi\CalderaRestApi;
use calderawp\caldera\Core\Tests\Traits\SharedFactories;
use calderawp\CalderaContainers\Service\Container;

abstract class TestCase extends \Mockery\Adapter\Phpunit\MockeryTestCase
{
	use  SharedFactories;


	public function setUp()
	{
		if( ! $_ENV ){
			$_ENV = [];
		}
		$_ENV[ 'JWT_SECRET' ] = '12322334';
		parent::setUp(); // TODO: Change the autogenerated stub
	}
}
